# Generated by Django 2.2.2 on 2019-06-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(through='users.Friends', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendsinviter', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendstarget', to='users.Profile'),
        ),
    ]
