# Generated by Django 2.2 on 2019-05-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_orginvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginvite',
            name='accepted',
            field=models.NullBooleanField(default=None),
        ),
    ]
