# Generated by Django 2.2 on 2019-05-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20190503_0025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orginvite',
            unique_together=set(),
        ),
    ]
