# Generated by Django 2.2 on 2019-05-03 03:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0011_auto_20190503_0106'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='orginvite',
        #     unique_together={('organization', 'inviter', 'target')},
        # ),
    ]
