# Generated by Django 2.2.2 on 2019-06-26 03:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0012_auto_20190503_0336'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orginvite',
            unique_together={('organization', 'target')},
        ),
    ]
