# Generated by Django 2.2.2 on 2019-06-17 20:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_task_creator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskassigment',
            unique_together={('user', 'task')},
        ),
    ]
