# Generated by Django 2.2.2 on 2019-06-11 02:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_auto_20190503_0336'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('member', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('member', 'group')},
        ),
    ]
