# Generated by Django 2.2.3 on 2019-07-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubmessages', '0002_auto_20190611_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(max_length=1500),
        ),
    ]
