# Generated by Django 2.2 on 2019-05-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='adminstrator',
            new_name='administrator',
        ),
    ]
