# Generated by Django 2.2 on 2019-05-03 00:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0006_orginvite_accepted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('organization', 'user')},
        ),
    ]
