# Generated by Django 2.2 on 2019-05-03 00:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0008_auto_20190503_0046'),
    ]

    operations = [
        
    ]
