# Generated by Django 2.2 on 2019-05-03 01:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0009_auto_20190503_0058'),
    ]

    operations = [
        
    ]
